---
name: Lint

on:
  pull_request:
    branches:
      - master

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Lint with prettier
        run: |
          yarn install --frozen-lockfile
          yarn prettier . --write

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
